MoveShareApplication/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MoveShareApplication.Models
{
    public class Order
    {
        [Key]
        public string Order_id { get; set; }


        //foreign key
        [Required]
        public string Item_id { get; set; }
        [ForeignKey("Item_id")]
        public Item? Item { get; set; }

        public int Order_quantity { get; set; }

        public DateTime Created_at { get; set; }

        public DateTime LastUpdate_at { get; set; }

        //Range Created, Cancelled, Pickedup
        [Required]
        public string Status { get; set; }
        //public OrderStatus Status { get; set; }


        //foreign key, 
        //remove cascade deletion from generated migration
        [Required]
        public string Customer_id { get; set; }
        [ForeignKey("Customer_id")]
        public IdentityUser? ApplicationUser { get; set; }

        /*
        public enum OrderStatus
        {
            Created,
            Cancelled,
            Rejected
        }
        */
    }
}

MoveShareApplication/Controllers/MoveShareController.cs
using Microsoft.AspNetCore.Mvc;
using MoveShareApplication.Data;
using System.Security.Claims;
using MoveShareApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MoveShareApplication.Authorization;
using Microsoft.CodeAnalysis;

namespace MoveShareApplication.Controllers
{

    /// <summary>
    /// _logger categories{
    ///     Exception,
    ///     DbUpdateException,
    ///     Sensitive Action Failed,
    ///     Sensitive Action Succeed,     
    /// }
    /// To Do: 
    ///     1, To save log into DB (separate Database, JSON format).
    ///     2, To add new log catetory : All Admin Action.
    /// </summary>

    [Authorize]
    public class MoveShareController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthorizationService _authorizationService;
        private readonly ILogger<MoveShareController> _logger;
        public MoveShareController(ApplicationDbContext db, IAuthorizationService authorizationService, ILogger<MoveShareController> logger)
        {
            _db = db;
            _authorizationService = authorizationService;
            _logger = logger;
        }


        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            try {
                IEnumerable<Item> available_item_list = _db.Item.Where(i => i.Available == true);
                return View(available_item_list);
                
            }
            catch (Exception ex) {
                _logger.LogInformation("Exception :" + ex);

            }
            return RedirectToAction("Index", "Home");
        }

        //Create function
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "Administrator,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Item obj)
        {

            /*
            //ModelState validation method report error, as it apply to associate Model's full property.
            //No elegant solution found yet for partial evaluation, besides create a mock ViewModel. Leave this this moment.
            
              [Bind(Include = "Description,Quantity,PickUpNote,Location")]

              if (!ModelState.IsValid)
              {
                  var errors = ModelState.Values.SelectMany(v => v.Errors);
                  return View(obj);
              }
           */

            obj.Item_id = Guid.NewGuid().ToString();
            obj.Owner_id = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            obj.Created_at = DateTime.Now;
            obj.LastUpdate_at = obj.Created_at;
            obj.Available = true;

            try
            {
                ModelState.Clear();
                if (!TryValidateModel(obj))
                {
                    //Debug: var errors = ModelState.Values.SelectMany(v => v.Errors);
                    _logger.LogInformation("Sensitive Action Failed : Create() : by user " + User.Identity + " : at " + obj.Created_at + " : issue - input validation failed " );
                    TempData["Fail"] = "Pls double check input";
                    return View();
                }

                _db.Item.Add(obj);
                await _db.SaveChangesAsync();
                
                _logger.LogInformation("Sensitive Action Succeed : Create() : by user " + User.Identity + " : at " + obj.Created_at);
                TempData["Success"] = "Item created successfully!";
                return RedirectToAction("Index");
            }
            catch (DbUpdateException ex)
            {
                _logger.LogInformation("DB exceptoin : Create() : " + ex);
                TempData["Fail"] = "Failed!";
                return RedirectToAction("Index");
            }

        }


        [HttpGet]
        public IActionResult Edit(string id)
        {
            //consider security text: scenario MITM attacker with proxy
            if (id == null) {
                return NotFound();
            }

            var findItem = _db.Item.Find(id);

            if (findItem == null) {
                return NotFound();
            }
            return View(findItem);
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(Item obj)
        {
            /*
            //ModelState validation method report error, as it apply to associate Model's full property.
            //No elegant solution found yet for partial evaluation, besides create a mock ViewModel. Leave this this moment.

              [Bind(Include = "Description,Quantity,PickUpNote,Location")]

              if (!ModelState.IsValid)
              {
                  var errors = ModelState.Values.SelectMany(v => v.Errors);
                  return View(obj);
              }
           */

            if (obj.Item_id == null)
            {
                return NotFound();
            }

            Item originalItem = _db.Item.Find(obj.Item_id);
            
            if (originalItem == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, originalItem, MoveShareItemOperation.Edit);
            
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            ModelState.Clear(); //important.tricky. Otherwise, following TryUpdateModelAsync wouldn't execute.(as modelstate evaluation would fail, due to we only bind to partial of the Item model)
            if (await TryUpdateModelAsync<Item>(originalItem, "", i => i.Name, i => i.Description, i => i.Quantity, i => i.PickUpNote, i => i.Location))
            {
                originalItem.LastUpdate_at = DateTime.Now;

                try
                {
                    await _db.SaveChangesAsync();
                }

                catch (DbUpdateException ex)
                {
                    _logger.LogInformation("DB exceptoin : EditPost() : " + ex);
                    return RedirectToAction("Index");
                }

                _logger.LogInformation("Sensitive Action Succeed : EditPost() : by user " + User.Identity + " : update at " + originalItem.LastUpdate_at);
                TempData["Success"] = "Item edited successfully!";
                return RedirectToAction("Index");
            }

            _logger.LogInformation("Sensitive Action Failed : EditPost() : by user " + User.Identity + " : at " + obj.Created_at + " : possible issue - input validation failed ");
            TempData["Fail"] = "Failed!";
            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult Delete(string id)
        {
            // to perform security test: fuzz, no int
            if (id == null)
            {
                return NotFound();
            }

            Item finditem = _db.Item.Find(id);

            if (finditem == null)
            {
                return NotFound();
            }

            return View(finditem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteItem(string Item_id)
        {


            //add logic: to handle not yet completed order, associated to the to be deleted item.

            if (Item_id == null)
            {
                return NotFound();
            }

            Item originalItem = _db.Item.Find(Item_id);

            if (originalItem == null)
            {
                return NotFound();
            }

           
            var isAuthorized = await _authorizationService.AuthorizeAsync(this.User, originalItem, MoveShareItemOperation.Delete);

            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            originalItem.Available = false;
            originalItem.LastUpdate_at = DateTime.Now;
            try
            {
                await _db.SaveChangesAsync();
            }
            catch(DbUpdateException ex)
            {
                _logger.LogInformation("DB exceptoin : DeleteItem() : " + ex);
                return RedirectToAction("Index");
            }

            _logger.LogInformation("Sensitive Action Succeed : DeleteItem() : by user " + User.Identity + " : update at " + originalItem.LastUpdate_at);
            TempData["Success"] = "Item deleted successfully!";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Order(string id)
        {
            return View();

        }


        //Order & Picture upload, relevant logic to be added

        /*
        [HttpPost]
        public IActionResult OrderItem(string id)
        {
            //Add logic to specify order quantity.

            var new_order = new Order();
            new_order.Order_id = Guid.NewGuid().ToString();
            new_order.Item_id = id;

            //new_order.Order_quantity =
            new_order.Created_at = DateTime.Now;
            new_order.LastUpdate_at = new_order.Created_at;
            new_order.Status = "Created";
            new_order.Customer_id = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            _db.Order.Add(new_order);
            _db.SaveChanges();
            TempData["Success"] = "Item Ordered successfully!";
            return RedirectToAction("Index");
        }
        */

    }
}

MoveShareApplication/Views/MoveShare/Create.cshtml
@model Item
@{
    ViewData["Title"] = "Create Item";
}

<partial name="_Warning" />

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Item to Share</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control"/>
            <span asp-validation-for="Quantity" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PickUpNote"></label>
            <input asp-for="PickUpNote" class="form-control"/>
            <span asp-validation-for="PickUpNote" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control"/>
            <span asp-validation-for="Location" class="text-bg-danger"></span>
        </div>

        <button type="submit" class="btn btn-info" style="width:150px">Create</button>
        <a asp-controller="MoveShare" asp-action="Index" class="btn btn-outline-dark" style="width:150px">Back to List</a>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    } 
}

MoveShareApplication/Views/MoveShare/Delete.cshtml
@model Item
@{
    ViewData["Title"] = "Delete Item";
}

<form method="post" asp-action="DeleteItem">
    <input asp-for="Item_id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete item</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="PickUpNote"></label>
            <input asp-for="PickUpNote" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" disabled class="form-control"/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    } 
}

MoveShareApplication/Views/MoveShare/Edit.cshtml
@model Item
@{
    ViewData["Title"] = "Edit Item";
}

<form method="post" asp-action="EditPost">
    <input asp-for="Item_id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Items</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control"/>
            <span asp-validation-for="Quantity" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PickUpNote"></label>
            <input asp-for="PickUpNote" class="form-control"/>
            <span asp-validation-for="PickUpNote" class="text-bg-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control"/>
            <span asp-validation-for="Location" class="text-bg-danger"></span>
        </div>

        <button type="submit" class="btn btn-info" style="width:150px">Edit</button>

</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />      
    } 
}

MoveShareApplication/Views/MoveShare/Index.cshtml
@using MoveShareApplication.Authorization
@using Microsoft.AspNetCore.Authorization
@using MoveShareApplication.Models


@inject IAuthorizationService AuthorizationService

@model IEnumerable<Item>
@{
    ViewData["Title"] = "Items available";
}

<partial name="_Warning" />

<div class="row" style="padding: 12px 0% 0% 0%">
    <div class="col-md-6">
       <h1 class="text-primary">Available  Items  List</h1>
    </div>
    <div class="col-md-6 text-end">
        <a asp-controller="MoveShare" asp-action="Create" class="btn btn-info">
            To Share
        </a>
    </div>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Reserve_for_pic</th>
            <th scope="col">Available Amount</th>
            <th scope="col">Location</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>
                    @obj.Name
                </td>
                <td>
                    @obj.Description
                </td>
                <td>
                    <p>reserve for pic</p>
                </td>
                <td>
                    @obj.Quantity
                </td>
                <td>
                    @obj.Location
                </td>
                <td>
                <div style="float: right">
                        @if ((await AuthorizationService.AuthorizeAsync(User, obj, MoveShareItemOperation.Edit)).Succeeded)
                        {
                            <a asp-controller="MoveShare" asp-action="Edit" asp-route-id="@obj.Item_id" class="btn btn-outline-warning">
                                Edit
                            </a>
                            <a asp-controller="MoveShare" asp-action="Delete" asp-route-id="@obj.Item_id" class="btn btn-outline-danger">
                                Delete
                            </a>
                        }
                        <a asp-controller="MoveShare" asp-action="Order" asp-route-id="@obj.Item_id" class="btn btn-outline-success">
                            Order
                        </a>
                    
                        

                </div>  
                
            </td>
            </tr>
        }
    </tbody>
</table>

MoveShareApplication/Views/MoveShare/Order.cshtml
@model IEnumerable<Item>
@{
    ViewData["Title"] = "Order";
}

<partial name="_Warning" />

<div class="row" style="padding: 20% 0% 0% 0%">
    <div class="col-md-6">
       <h1 class="text-primary">Logic to be added</h1>
    </div>
</div>